version: "3.9"
services:
  react-keycloak:
    image: quay.io/keycloak/keycloak:20.0.3
    ports:
      - 10301:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./import:/opt/keycloak/data/import:ro
    command: start-dev --import-realm
